config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users
  resources :articles
  resources :users do
    resources :friendships, :shallow => true
    resources :article_users, :shallow => true
  end
  get 'users/:id' => 'users#show'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :users, through: :article_users
  has_many :article_users, dependent: :destroy
end

app/models/article_user.rb
class ArticleUser < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friends, :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friends, :through => :friendships
  has_many :friendships, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

end

app/controllers/article_users_controller.rb
class ArticleUsersController < ApplicationController
  before_action :set_article_user, only: [:show, :edit, :update, :destroy]

  # GET /article_users
  # GET /article_users.json
  def index
    @article_users = ArticleUser.all
  end

  # GET /article_users/1
  # GET /article_users/1.json
  def show
  end

  # GET /article_users/new
  def new
    @article_user = ArticleUser.new
  end

  # GET /article_users/1/edit
  def edit
  end

  # POST /article_users
  # POST /article_users.json
  def create
    @article_user = ArticleUser.new(article_user_params)

    @article_user.user_id = params[:user_id]

      if @article_user.save
        format.html { redirect_to @article_user.article, notice: 'Article user was successfully created.' }
      else
        format.html { render :new }
      end
  end

  # PATCH/PUT /article_users/1
  # PATCH/PUT /article_users/1.json
  def update
    respond_to do |format|
      if @article_user.update(article_user_params)
        format.html { redirect_to @article_user, notice: 'Article user was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_user }
      else
        format.html { render :edit }
        format.json { render json: @article_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_users/1
  # DELETE /article_users/1.json
  def destroy
    @article_user.destroy
    respond_to do |format|
      format.html { redirect_to article_users_url, notice: 'Article user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_user
      @article_user = ArticleUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_user_params
      params.require(:article_user).permit(:article_id, :user_id)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @users = User.all
    @friends = current_user.friendships.map { |friend| User.find(friend.friend_id) }
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article_user = @article.article_users.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @response = HTTParty.get("http://api.smmry.com/&SM_API_KEY=A252EB9549&SM_LENGTH=5&SM_URL=#{@article.URL}")
    if !@article.title.present?
      @article.title = @response["sm_api_title"]
    end
    @article.content = @response["sm_api_content"]
    @article.char_count = @response["sm_api_character_count"]
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :char_count, :URL, :private, :user_id)
    end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]
  def show
    @friendship = @user.friendships.new
  end

  def new
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.new(friendship_params)
    @friendship.user_id = current_user.id
    redirect_to root_url

    # get the new friendship's friend_id out of the params
    @friendship.friend_id = params[:friend_id]

    if @friendship.save
      flash[:notice] = "Added friend"
      redirect_to root_url
    else
      flash[:notice] = "Unable to add friend"
      redirect_to root_url
    end
  end

  private

    def friendship_params
      params.require(:friendship).permit(:id, :user_id, :friend_id)
    end

    def get_friends
      shared_friendships = Friendship.all.map { |user| user if user.user_id == self.id }.compact
      shared_users = shared_image_users.map { |u| User.find(u.user_id) }.compact
      user = User.all.map {|u| u if u.id == self.user_id }.compact
      users_array = User.all - shared_users - user
      # Need to format here with username then email
      users_array.map { |user| [user.name + " (" + user.email + ")", user.id]}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @friends = current_user.friendships.map { |friend| User.find(friend.friend_id) }
    @article_url = "http://www.theverge.com/2016/7/10/12127638/uber-ergo-investigation-lawsuit-fraud-travis-kalanick"
    #@response = HTTParty.get("http://api.smmry.com/&SM_API_KEY=A252EB9549&SM_LENGTH=5&SM_URL=#{@article_url}")
    @character_count = 1#@response["sm_api_character_count"]
    @article_title = "Test title" #@response["sm_api_title"]
    @summary = "Test summary"#@response["sm_api_content"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_users_helper.rb
module ArticleUsersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/article_users/_form.html.erb
<%= form_for(@article_user) do |f| %>
  <% if @article_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article_user.errors.count, "error") %> prohibited this article_user from being saved:</h2>

      <ul>
      <% @article_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/article_users/edit.html.erb
<h1>Editing Article User</h1>

<%= render 'form' %>

<%= link_to 'Show', @article_user %> |
<%= link_to 'Back', article_users_path %>

app/views/article_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Article Users</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_users.each do |article_user| %>
      <tr>
        <td><%= article_user.article %></td>
        <td><%= article_user.user %></td>
        <td><%= link_to 'Show', article_user %></td>
        <td><%= link_to 'Edit', edit_article_user_path(article_user) %></td>
        <td><%= link_to 'Destroy', article_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article user', new_article_user_path %>

app/views/article_users/new.html.erb
<h1>New Article User</h1>

<%= render 'form' %>

<%= link_to 'Back', article_users_path %>

app/views/article_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @article_user.article %>
</p>

<p>
  <strong>User:</strong>
  <%= @article_user.user %>
</p>

<%= link_to 'Edit', edit_article_user_path(@article_user) %> |
<%= link_to 'Back', article_users_path %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>Please submit a URL to an article you'd like to summarize.  By default the article's title will be picked but if you would like to enter a custom one go right ahead!</p><br>

<div class="input-group">
  <div class="field">
    <%= f.text_area :title, placeholder: "Custom Title", class: "input-group-addon" %>
  </div>
</div>
  <div class="field">
    <%= f.label :URL %><br>
    <%= f.text_area :URL %>
  </div>
  <div class="field">
    <%= f.radio_button :private, '0', :checked => true %> <%= f.label :private, "Public" %>
    <%= f.radio_button :private, '1' %> <%= f.label :private, "Private" %>
  </div>
  <br>
  <%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure you want to delete this article?' } %> |

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="friendlist">
  <h3>Current Friends</h3>
  <% @friends.each do |friend| %>
    <% if !friend.new_record? %>
      <div class="friend">
        <%= image_tag(friend.avatar, size: "40x40", alt: friend.avatar) %>
        <h4><%= link_to friend.username, user_path(friend.id) %></h4>
      </div>
    <% end %>
  <% end %>
  <h4><%= link_to "Add New Friend", new_user_friendship_path(current_user.id) %></h4>
</div>
<br><br>
<h3>Listing Articles</h3>
<div class="row masonry-container">
  <div class="box col-md-2 article">
    <h4><%= link_to "New Article", new_article_path %></h4>
    Click the title above to visit the article creation page.
  </div>
<% @articles.each do |article| %>
  <% if article.private == false %>
  <div class="box col-md-4 article">
        <h4><%= link_to article.title, article %><small> - <%= User.find(article.user_id).username  %>
        <% if article.user_id == current_user.id %>
          <%= link_to 'Edit', edit_article_path(article) %>
          <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %></small></h4>
        <%= article.content %>
  </div>
  <% end %>
<% end %>
</div>

app/views/articles/show.html.erb
<% if @article.private == true %>
  <% if @article.user_id == current_user.id %>
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Title:</strong>
      <%= @article.title %>
    </p>
    <p>
      <strong>Content:</strong>
      <%= @article.content %>
    </p>
    <p>
      <strong>Char count:</strong>
      <%= @article.char_count %>
    </p>
    <p>
      <strong>URL:</strong>
      <%= link_to @article.URL, @article.URL %>
    </p>
    <%= link_to 'Edit', edit_article_path(@article) %> |
  <% else %>
    <h1>Stop poking around here!</h1>
  <% end %>
<% else %>
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Title:</strong>
      <%= @article.title %>
    </p>
    <p>
      <strong>Content:</strong>
      <%= @article.content %>
    </p>
    <p>
      <strong>Char count:</strong>
      <%= @article.char_count %>
    </p>
    <p>
      <strong>URL:</strong>
      <%= link_to @article.URL, @article.URL %>
    </p>
    <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

app/views/friendships/_form.html.erb
<% @friends = current_user.friendships.map { |friend| User.find(friend.friend_id) } %>
<% @users_left = User.all - @friends%>

<% @users_left.each do |user| %>
<% if user.id != current_user.id %>
<%= form_tag(new_user_friendship_path, method: "get") do %>
  <%= image_tag(user.avatar, size: "40x40", alt: user.avatar) %>
  <h4><%= link_to user.username, user_path(user.id) %></h4>
  <%= hidden_field_tag :friend_id, user.id%>
  <div class="actions">
    <%= submit_tag("NewFriend") %>
  </div>
<% end %>
<% end %>
<% end %>

app/views/friendships/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/home/index.html.erb
<div id="friendlist">
  <h3>Current Friends</h3>
  <% @friends.each do |friend| %>
    <% if !friend.new_record? %>
      <%= link_to friend.username, user_path(friend.id) %>
      <%= image_tag(friend.avatar, size: "50x50", alt: friend.avatar) %><br>
    <% end %>
  <% end %>
</div>
<%= link_to "New Article", new_article_path %>
<div id="article">
  <h3><%= @article_title %></h3>
  <p><%= @summary %></p>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Demo App", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Posts', '#' %></li>
                <% if current_user %>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andromeda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class="bg-img">
<body>

    <div id="main-title">
      Andromeda
    </div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= link_to current_user.email, user_path(current_user.id) %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</div>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div id="container">
  <% if @user.id == current_user.id %>
  <h1>My Profile</h1><p><%= link_to "Edit profile", edit_user_registration_path %></p><br>
<% @articles = Article.all %>
<% @articles.each do |article| %>
  <div class="box col-md-4 article">
        <h4><%= link_to article.title, article %><small> - <%= User.find(article.user_id).username  %>
          <%= link_to 'Edit', edit_article_path(article) %>
          <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></small></h4>
        <%= article.content %>
  </div>
<% end %>

  <% else %>
    <h3><%= @user.username + "'s Profile" %></h3>
  <% end %>
  <h3><%= image_tag(@user.avatar, size: "100x100", alt: @user.avatar) %></h3><br>
  <h3>First Name: <%= @user.first_name %></h3>
  <h3>Last Name: <%= @user.last_name %></h3><br>

  <p><%= link_to "Back", root_url %></p>
</div>